### ISSUE TITLE
cjdns: does not compile with gcc 14

### ISSUE THREAD

**Issue by dph5199278** [openwrt/routing#1083]
Maintainer: @wfleurant 
Environment: 
arch: x86_64
OpenWrt version: main

Description:
Error Output:
```
cc1: note: someone does not honour COPTS correctly, passed 15 times
exception/Er.c: In function 'Er__raise':
exception/Er.c:46:64: error: 'Allocator__calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
   46 |         struct Er_Ret* res = Allocator_calloc(alloc, sizeof(struct Er_Ret), 1);
      |                                                                ^~~~~~
exception/Er.c:46:64: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors

    at error (/opt/openwrt/build_dir/target-x86_64_musl/cjdns-cjdns-v21.1/node_build/builder.js:104:15)
    at /opt/openwrt/build_dir/target-x86_64_musl/cjdns-cjdns-v21.1/node_build/builder.js:185:29
    at /opt/openwrt/build_dir/target-x86_64_musl/cjdns-cjdns-v21.1/node_build/builder.js:150:17
    at ChildProcess.<anonymous> (/opt/openwrt/build_dir/target-x86_64_musl/cjdns-cjdns-v21.1/node_modules/saferphore/index.js:22:34)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:351:12)
```

**Comment by BKPepe** [comment]
This could be fixed by @Ansuel's fix https://github.com/openwrt/routing/commit/0bf1ec3c3d9459ce8dc6fa7e1b6084518a0b5a55
