### ISSUE TITLE
cjdns can not be compiled with current OpenWrt master

### ISSUE THREAD

**Issue by BKPepe** [openwrt/routing#958]
Maintainer: @wfleurant 
Environment:
This was discovered by CI in  https://github.com/openwrt/routing/pull/954
 - Same happens to me while building all packages for Turris routers in dev env. where building OpenWrt master

Description:

```
cc1: note: someone does not honour COPTS correctly, passed 16 times
net/SwitchPinger_admin.c: In function 'adminPing':
net/SwitchPinger_admin.c:103:133: error: dangling pointer 'err' to an unnamed temporary may be used [-Werror=dangling-pointer=]
  103 |         Dict d = Dict_CONST(String_CONST("error"), String_OBJ(err), NULL);
      |                                                                                                                                     ^
net/SwitchPinger_admin.c:82:26: note: unnamed temporary defined here
   82 |         err = String_CONST("path was not parsable.");
      |                          ^
cc1: all warnings being treated as errors

    at error (/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/cjdns-cjdns-v21.1/node_build/builder.js:104:15)
    at /home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/cjdns-cjdns-v21.1/node_build/builder.js:185:29
    at /home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/cjdns-cjdns-v21.1/node_build/builder.js:150:17
    at ChildProcess.<anonymous> (/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/cjdns-cjdns-v21.1/node_modules/saferphore/index.js:22:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
make[2]: *** [Makefile:149: /home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/cjdns-cjdns-v21.1/.built] Error 1
```

**Comment by wfleurant** [comment]
oops, should be fixed now.
